services:
  smallweb:
    image: ghcr.io/pomdtr/smallweb:latest
    container_name: smallweb
    restart: unless-stopped
    ports:
      - 7777:7777
      - 2222:2222
    volumes:
      - ./workspace:/home/smallweb/workspace
    environment:
      - SMALLWEB_DIR=/home/smallweb/workspace
      - SMALLWEB_DOMAIN=smallweb.localhost
