services:
  smallweb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SMALLWEB_DOMAIN=localhost
    ports:
      - "7777:7777"
    volumes:
      - ./example:/smallweb
