services:
  smallweb:
    image: ghcr.io/pomdtr/smallweb:latest
    volumes:
      - ./examples:/smallweb
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
