//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BatchRequestMode.
const (
	Deferred BatchRequestMode = "deferred"
	Read     BatchRequestMode = "read"
	Write    BatchRequestMode = "write"
)

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	Mode       *BatchRequestMode              `json:"mode,omitempty"`
	Statements []BatchRequest_Statements_Item `json:"statements"`
}

// BatchRequestMode defines model for BatchRequest.Mode.
type BatchRequestMode string

// BatchRequestStatements0 defines model for .
type BatchRequestStatements0 = string

// BatchRequest_Statements_Item defines model for BatchRequest.statements.Item.
type BatchRequest_Statements_Item struct {
	union json.RawMessage
}

// ExecuteRequest defines model for ExecuteRequest.
type ExecuteRequest struct {
	Statement ExecuteRequest_Statement `json:"statement"`
}

// ExecuteRequestStatement0 Simple SQL statement string
type ExecuteRequestStatement0 = string

// ExecuteRequest_Statement defines model for ExecuteRequest.Statement.
type ExecuteRequest_Statement struct {
	union json.RawMessage
}

// ExecuteResult defines model for ExecuteResult.
type ExecuteResult struct {
	ColumnTypes     *[]string        `json:"columnTypes,omitempty"`
	Columns         *[]string        `json:"columns,omitempty"`
	LastInsertRowid *int64           `json:"lastInsertRowid"`
	Rows            *[][]interface{} `json:"rows,omitempty"`
	RowsAffected    *int64           `json:"rowsAffected,omitempty"`
}

// StatementObject defines model for StatementObject.
type StatementObject struct {
	Args *StatementObject_Args `json:"args,omitempty"`
	Sql  string                `json:"sql"`
}

// StatementObjectArgs0 defines model for .
type StatementObjectArgs0 = []interface{}

// StatementObjectArgs1 defines model for .
type StatementObjectArgs1 map[string]interface{}

// StatementObject_Args defines model for StatementObject.Args.
type StatementObject_Args struct {
	union json.RawMessage
}

// GetBlobParams defines parameters for GetBlob.
type GetBlobParams struct {
	Accept *string `json:"Accept,omitempty"`
}

// BatchSQLiteJSONRequestBody defines body for BatchSQLite for application/json ContentType.
type BatchSQLiteJSONRequestBody = BatchRequest

// ExecuteSQLiteJSONRequestBody defines body for ExecuteSQLite for application/json ContentType.
type ExecuteSQLiteJSONRequestBody = ExecuteRequest

// AsBatchRequestStatements0 returns the union data inside the BatchRequest_Statements_Item as a BatchRequestStatements0
func (t BatchRequest_Statements_Item) AsBatchRequestStatements0() (BatchRequestStatements0, error) {
	var body BatchRequestStatements0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBatchRequestStatements0 overwrites any union data inside the BatchRequest_Statements_Item as the provided BatchRequestStatements0
func (t *BatchRequest_Statements_Item) FromBatchRequestStatements0(v BatchRequestStatements0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBatchRequestStatements0 performs a merge with any union data inside the BatchRequest_Statements_Item, using the provided BatchRequestStatements0
func (t *BatchRequest_Statements_Item) MergeBatchRequestStatements0(v BatchRequestStatements0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatementObject returns the union data inside the BatchRequest_Statements_Item as a StatementObject
func (t BatchRequest_Statements_Item) AsStatementObject() (StatementObject, error) {
	var body StatementObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatementObject overwrites any union data inside the BatchRequest_Statements_Item as the provided StatementObject
func (t *BatchRequest_Statements_Item) FromStatementObject(v StatementObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatementObject performs a merge with any union data inside the BatchRequest_Statements_Item, using the provided StatementObject
func (t *BatchRequest_Statements_Item) MergeStatementObject(v StatementObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BatchRequest_Statements_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BatchRequest_Statements_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsExecuteRequestStatement0 returns the union data inside the ExecuteRequest_Statement as a ExecuteRequestStatement0
func (t ExecuteRequest_Statement) AsExecuteRequestStatement0() (ExecuteRequestStatement0, error) {
	var body ExecuteRequestStatement0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExecuteRequestStatement0 overwrites any union data inside the ExecuteRequest_Statement as the provided ExecuteRequestStatement0
func (t *ExecuteRequest_Statement) FromExecuteRequestStatement0(v ExecuteRequestStatement0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExecuteRequestStatement0 performs a merge with any union data inside the ExecuteRequest_Statement, using the provided ExecuteRequestStatement0
func (t *ExecuteRequest_Statement) MergeExecuteRequestStatement0(v ExecuteRequestStatement0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatementObject returns the union data inside the ExecuteRequest_Statement as a StatementObject
func (t ExecuteRequest_Statement) AsStatementObject() (StatementObject, error) {
	var body StatementObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatementObject overwrites any union data inside the ExecuteRequest_Statement as the provided StatementObject
func (t *ExecuteRequest_Statement) FromStatementObject(v StatementObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatementObject performs a merge with any union data inside the ExecuteRequest_Statement, using the provided StatementObject
func (t *ExecuteRequest_Statement) MergeStatementObject(v StatementObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExecuteRequest_Statement) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExecuteRequest_Statement) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStatementObjectArgs0 returns the union data inside the StatementObject_Args as a StatementObjectArgs0
func (t StatementObject_Args) AsStatementObjectArgs0() (StatementObjectArgs0, error) {
	var body StatementObjectArgs0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatementObjectArgs0 overwrites any union data inside the StatementObject_Args as the provided StatementObjectArgs0
func (t *StatementObject_Args) FromStatementObjectArgs0(v StatementObjectArgs0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatementObjectArgs0 performs a merge with any union data inside the StatementObject_Args, using the provided StatementObjectArgs0
func (t *StatementObject_Args) MergeStatementObjectArgs0(v StatementObjectArgs0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatementObjectArgs1 returns the union data inside the StatementObject_Args as a StatementObjectArgs1
func (t StatementObject_Args) AsStatementObjectArgs1() (StatementObjectArgs1, error) {
	var body StatementObjectArgs1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatementObjectArgs1 overwrites any union data inside the StatementObject_Args as the provided StatementObjectArgs1
func (t *StatementObject_Args) FromStatementObjectArgs1(v StatementObjectArgs1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatementObjectArgs1 performs a merge with any union data inside the StatementObject_Args, using the provided StatementObjectArgs1
func (t *StatementObject_Args) MergeStatementObjectArgs1(v StatementObjectArgs1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StatementObject_Args) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StatementObject_Args) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Remove blob item or clear with prefix
	// (DELETE /blob/{key})
	DeleteBlob(w http.ResponseWriter, r *http.Request, key string)
	// Get or list blob items
	// (GET /blob/{key})
	GetBlob(w http.ResponseWriter, r *http.Request, key string, params GetBlobParams)
	// Check if blob item exists
	// (HEAD /blob/{key})
	HasBlob(w http.ResponseWriter, r *http.Request, key string)
	// Set blob item
	// (PUT /blob/{key})
	SetBlob(w http.ResponseWriter, r *http.Request, key string)
	// Execute a batch of SQLite statements in a transaction
	// (POST /sqlite/batch)
	BatchSQLite(w http.ResponseWriter, r *http.Request)
	// Execute a single SQLite statement
	// (POST /sqlite/execute)
	ExecuteSQLite(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteBlob operation middleware
func (siw *ServerInterfaceWrapper) DeleteBlob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBlob(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBlob operation middleware
func (siw *ServerInterfaceWrapper) GetBlob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBlobParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBlob(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HasBlob operation middleware
func (siw *ServerInterfaceWrapper) HasBlob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HasBlob(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetBlob operation middleware
func (siw *ServerInterfaceWrapper) SetBlob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetBlob(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchSQLite operation middleware
func (siw *ServerInterfaceWrapper) BatchSQLite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchSQLite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteSQLite operation middleware
func (siw *ServerInterfaceWrapper) ExecuteSQLite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteSQLite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/blob/{key}", wrapper.DeleteBlob)
	m.HandleFunc("GET "+options.BaseURL+"/blob/{key}", wrapper.GetBlob)
	m.HandleFunc("HEAD "+options.BaseURL+"/blob/{key}", wrapper.HasBlob)
	m.HandleFunc("PUT "+options.BaseURL+"/blob/{key}", wrapper.SetBlob)
	m.HandleFunc("POST "+options.BaseURL+"/sqlite/batch", wrapper.BatchSQLite)
	m.HandleFunc("POST "+options.BaseURL+"/sqlite/execute", wrapper.ExecuteSQLite)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXS2/jNhD+K8S0R9XytmkPuiXtdmug6Kbx3oIcaGlkc0OR8nDkBwz994KUY1sPG9k6",
	"AfYUOeS8vu+b0WgHqS1Ka9Cwg2QHLl1gIcPjneR08YDLCh373yXZEokVhtPCZuj/oqkKSB6BUGYQwZoU",
	"I0SQYY5EmMFTBLwtERJwTMrMoY7AsWQsXkIqxiI8WIOfc0gedz2LHfxImEMCP8THdON9rvH0xd3n2VdM",
	"Geqn+hBUEskt1HUEhMtK+YySx9MEjvnZvXUEHzeYVoxnaz+Yt7PO0KWkSlbWQAJTVZQaxfTfv8XhvthX",
	"FF1f4bmKLhfkKj1QT2p1VZgv2xLbhPSIa4Ma7Q2/0UhLxxPjkPjBrlXmbXJLhWRIQBn+7QYiMJXWcqYR",
	"EqYKDz6UYZwjeS9k1+24Lw8DEbu/ve1tnmPKOBy+G64ewLTLSQ9VSfOOrM+nuAOZZcorR+r7Uy/9yF7c",
	"bqkHoO5KYqkHxOBvKZNbb98W7O39ROSWxLSQWq9xJmbazoRjS3KOQprMa1kxCp+e9EbOQ6XY0wQHq9v7",
	"CUSwQnKN2w+j8WjsAbMlGlkqSOCX0XjkYS4lLwJEsQ8V755xWzd5aeQwXQ6hJhkk8Ef4/522s2BMskBG",
	"cgPN92WBTfrPuB2JaZXnaiPWihciFpZEarU1gq1INUoSUuvmsCTM1WYEHiJIQn5ejLLwFT7jFk4RbpTZ",
	"tOgQG0/+siutcY0efh6Pm2YzvB8djBuOSy19sN0FT3XUnS1VmqJzHtVfG6/t84lhJCO1mCKtkMRHItvI",
	"2FVFIWkLCTxgYVd7lLwwAy4BjhMofIQ5cp+KT8hvyYNWjv0d90bYR7vGywJlhnT0c5umWDJcR5ssS63S",
	"gEX81dkOea8dhHXUcmRTRv7JMaEs2g4P02mmjKcuGuj7t1DSzfimr6R/LIs/bWWyq7T2CdnTHVg+CC4E",
	"9QT11fWXdMPqer+27BTlGwI3yvF5aMIdY1nkDT6tin9fYPosVH7SX0d3ZTXQUdNzHfVWNYdl5s5m2wty",
	"vkaFdTej+vsegFM8EWM4i91SK8Z45jff8EK3boCpsBg370J4LbD9OXFp32ut3v8L2VfOqEtJtJfG/vy6",
	"PEsGSLmTmTgUdQVx+8SEFIEoYfOXzeS41wtlhBRM0jiZBt+nBGPj4TzF+xDvSnLnK+MdaP4Gdr8HNp0y",
	"8+aLqcVlk5wLHoZ2DL+3rj5ABBVpSCBeffBL8n8BAAD//wlMig7ZDgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
